language: python
cache: pip
addons:
  apt:
    packages:
      - librrd-dev
      - rrdtool

python:
  - "2.7"
  - "3.4"
  - "3.6"

services:
  - postgres

before_install:
  - pip install -q codecov psycopg2 factory-boy testfixtures
  - pip install -e git+https://github.com/modoboa/modoboa#egg=modoboa

install:
  - pip install -r requirements.txt
  - python setup.py -q develop

before_script:
  - psql -c 'create database modoboa_test;' -U postgres

script:
  - cd test_project
  - coverage run --source ../modoboa_stats manage.py test modoboa_stats

after_success:
  - codecov

